analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.63068
title: Freelance Musician. Cigar Blogger.
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.7078206459991634
  brandStrength: 0.3800432702992111
  rhythmicContrast: 0.9348654109053314
  brandColors:
    - '#fefefc'
    - '#1a171a'
    - '#654127'
    - '#d0bc96'
    - '#9a8b6c'
  lightness: 0.4763752173166722
purpose: []
favicon: null
name: Jon Siddle
typography_spectrum: 0.2087
