name: Jon Siddle
favicon: null
layout_spectrum: 0.54246
typography_spectrum: 0.54512
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Freelance Musician. Cigar Blogger.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#3d3b49'
    - '#bfb1c2'
    - '#9f8c99'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
